### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by MrNinja93** [timstableford/MinecraftConfigs#3]
- [x] Unify Oregen, Forestry config left
- [x] Test new graves loot gen config
- [x] Test OreDistribution
- [x] Test Quark clay oregen
- [x] Test DeepResonance config
- [x] Tweak Quark shedding/Test
- [x] TConstruct rendering config
- [x] Forestry lepidopterology tweaks
- [x] Test NPE from gene samples in JEI - Fixed
- [x] <s>Stone generation tweak - Granite etc. **Failed** </s>
- [x] Disable annoying graves pop-up...
- [x] custom ruins world gen 
- [x] Fix custom ruins buged load

**Long term**
- [x] Find occlusion culling scene erroring cause, potentially minecraft itself

**Maybe**
- [x] Tweak Mekansim teleporting cost/heavy water gen as 1.7.10 server version? @timstableford  

**For final server version**
- [x]  enable quark stdout debug message suppressing [disabled while I test things]

**Comment by timstableford** [comment]
I think tweaking them required changing the code base didn't it? We could do that if you think it's a good plan?

**Comment by timstableford** [comment]
Is it that popup a random amount of time after you join where is says "If you see this thing it's probably a loot chest"?

**Comment by MrNinja93** [comment]
Yeah that annoying thing, theres a config option to disable it.
